//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GPSLink.rc
//
#define IDR_MAIN_MENUBAR                101
#define IDM_MAIN_MENUBAR                102
#define IDI_MAIN_ICON                   103
#define IDD_MAIN_DIALOG                 104
#define IDD_ABOUTBOX                    105
#define IDI_EPICS_ICON                  106
#define IDD_PROGRESS                    108
#define IDB_COMPASS                     109
#define IDD_FILEOPTS                    110
#define IDM_MAPMENU                     111
#define IDD_CALIBRATE                   112
#define IDM_PVTMENU                     113
#define IDD_EDITWAYPOINT                114
#define IDD_COLORS                      115
#define IDM_LVPOPUPMENU                 116
#define IDD_EDITTRACKPOINT              117
#define IDD_COMPORT                     118
#define IDD_GAMMA                       119
#define IDC_EDIT1                       1001
#define IDC_EDIT                        1002
#define IDI_ABOUT_ICON                  1003
#define IDC_LISTBOX                     1004
#define IDC_PROGRESS                    1005
#define IDC_PROGRESS_MSG                1006
#define IDC_SAVE_WPT                    1007
#define IDC_SAVE_TRK                    1008
#define IDC_SAVE_RTE                    1009
#define IDC_SAVE_CHECKEDONLY            1010
#define IDC_SAVE_MAP                    1011
#define IDC_SAVE_SHORTMAPNAME           1012
#define IDC_SAVE_MAPSHORTNAME           1013
#define IDC_LATENTRY                    1014
#define IDC_LONENTRY                    1015
#define IDC_ALTENTRY                    1016
#define IDC_NAMEENTRY                   1017
#define IDC_XCALC                       1018
#define IDC_YCALC                       1019
#define IDC_CALCOMBO                    1020
#define IDC_WPTCOMBO                    1021
#define IDC_CALLIST                     1022
#define IDC_WPTLIST                     1023
#define IDC_CALCOLORLIST                1024
#define IDC_WPTCOLORLIST                1025
#define IDC_XENTRY                      1026
#define IDC_RTECOLORLIST                1027
#define IDC_YENTRY                      1028
#define IDC_CALCLATLON                  1029
#define IDC_LATCALC                     1030
#define IDC_LONCALC                     1031
#define IDDELETE                        1032
#define IDREPLACE                       1033
#define IDC_TRKCOLORLIST                1034
#define IDADD                           1035
#define IDEDITCAL                       1036
#define IDCOPYALLCAL                    1037
#define IDDISPLAYCAL                    1038
#define IDC_POSCOLORLIST                1039
#define IDCOPYCAL                       1040
#define IDDISPLAYWPT                    1041
#define IDCOPYWPT                       1042
#define IDC_SYMBOL                      10040
#define IDC_CHECK1                      10041
#define IDC_CHECKLATLON                 10042
#define IDC_BUILDDATE                   10043
#define IDC_VERSION                     10044
#define IDC_WAYPOINTTYPE                10045
#define IDC_TRACKSTART                  10046
#define IDC_TRACKCONTINUE               10047
#define IDC_TRACKNAME                   10048
#define IDC_INDEXENTRY                  10049
#define IDC_COM1                        10050
#define IDC_COM2                        10051
#define IDC_COM3                        10052
#define IDC_COM4                        10053
#define IDC_OTHER                       10054
#define IDDEFAULT                       10055
#define IDRESTORE                       10056
#define IDC_PREVIEW                     10057
#define IDC_GAMMASLIDER                 10058
#define IDC_GAMMAENTRY                  10059
#define IDC_LIGHT                       10060
#define IDC_MEDIUM                      10061
#define ID_FILE                         40001
#define ID_HELP                         40002
#define ID_HELP_ABOUT                   40003
#define IDS_APP_TITLE                   40004
#define ID_FILE_QUIT                    40005
#define ID_TOOLS_QUIT                   40006
#define IDS_APP_CLASS                   40007
#define ID_FILE_RUN                     40008
#define ID_FILE_CLEAR                   40009
#define ID_TOOLS                        40010
#define ID_TOOLS_CLEAR                  40011
#define ID_TOOLS_CONNECT                40012
#define ID_TOOLS_DISCONNECT             40013
#define ID_TOOLS_GETID                  40014
#define ID_TOOLS_PVTDATA_START          40015
#define ID_TOOLS_PVTDATA_STOP           40016
#define ID_TOOLS_DOWNLOAD_WAYPOINTS     40017
#define ID_TOOLS_DOWNLOAD_ROUTES        40018
#define ID_TOOLS_DOWNLOAD_TRACKS        40019
#define ID_TOOLS_DOWNLOAD_ALL           40020
#define ID_TOOLS_UPLOAD_WAYPOINTS       40021
#define ID_TOOLS_UPLOAD_ROUTES          40022
#define ID_TOOLS_UPLOAD_TRACKS          40023
#define ID_TOOLS_UPLOAD_ALL             40024
#define ID_VIEW                         40025
#define ID_VIEW_WAYPOINTS               40026
#define ID_VIEW_ROUTES                  40027
#define ID_VIEW_TRACKS                  40028
#define ID_FILE_SAVE                    40029
#define ID_FILE_SAVEAS                  40030
#define IDS_CAP_FILE                    40031
#define IDS_CAP_EDIT                    40032
#define IDS_CAP_VIEW                    40033
#define IDS_CAP_TOOLS                   40034
#define IDS_CAP_HELP                    40035
#define ID_VIEW_CONSOLE                 40036
#define ID_FILE_OPEN                    40037
#define ID_CONSOLE                      40038
#define ID_WPT_LISTVIEW                 40039
#define ID_RTE_LISTVIEW                 40040
#define ID_TRK_LISTVIEW                 40041
#define ID_MAP_WINDOW                   40042
#define ID_MAP_COMPASS                  40043
#define ID_MAP_CURPOS                   40044
#define ID_TOOLS_ABORTTRANSFER          40045
#define ID_VIEW_MAP                     40046
#define ID_EDIT                         40047
#define ID_EDIT_CUT                     40048
#define ID_EDIT_COPY                    40049
#define ID_EDIT_DELETE_ALL              40050
#define ID_EDIT_DELETE_ALLWAYPOINTS     40051
#define ID_EDIT_DELETE_ALLROUTES        40052
#define ID_EDIT_DELETE_ALLTRACKS        40053
#define ID_EDIT_PASTE_BEFORE            40054
#define ID_EDIT_PASTE_AFTER             40055
#define ID_EDIT_DELETE_ALLSELECTED      40056
#define ID_TOOLS_RESET                  40057
#define ID_EDIT_DELETE_ALLCHECKED       40058
#define ID_EDIT_DELETE_ALLUNCHECKED     40059
#define ID_EDIT_PASTE_ATTOP             40060
#define ID_EDIT_PASTE_ATBOTTOM          40061
#define ID_EDIT_PASTE_ON                40062
#define IDM_MAPPOPUP                    40063
#define IDS_CAP_MAPOPTIONS              40064
#define ID_MAPOPTIONS_CENTER            40065
#define ID_MAPOPTIONS_CALIBRATE         40066
#define ID_MAPOPTIONS_POSITION_TOP      40067
#define ID_MAPOPTIONS_POSITION_BOTTOM   40068
#define ID_MAPOPTIONS_ZOOM_OUT5         40069
#define ID_MAPOPTIONS_ZOOM400           40070
#define ID_MAPOPTIONS_ZOOM_OUT          40071
#define ID_MAPOPTIONS_ZOOM200           40072
#define ID_MAPOPTIONS_ZOOM_NORMAL       40073
#define ID_MAPOPTIONS_ZOOM100           40074
#define ID_MAPOPTIONS_ZOOM_IN           40075
#define ID_MAPOPTIONS_ZOOM50            40076
#define ID_MAPOPTIONS_ZOOM_IN5          40077
#define ID_MAPOPTIONS_ZOOM25            40078
#define ID_MAPOPTIONS_REMOVEIMAGE       40079
#define ID_MAPOPTIONS_RESTORE           40080
#define ID_MAPOPTIONS_SHOWCOMPASS       40081
#define ID_MAPOPTIONS_CENTERHIGH        40082
#define ID_MAPOPTIONS_CENTERLOW         40083
#define ID_MAPOPTIONS_CALIBRATIONPOINTS 40084
#define ID_VIEW_TRACKSUMMARY            40085
#define ID_VIEW_ROUTESUMMARY            40086
#define ID_MAPOPTIONS_NEWWAYPOINT       40087
#define ID_TOOLS_OPTIONS                40088
#define ID_TOOLS_OPTIONS_COLORS         40089
#define ID_MAPOPTIONS_TRACKPOINTS       40099
#define ID_MAPOPTIONS_LEFTTOP           40100
#define ID_PVTOPTIONS_STOP              40101
#define ID_PVTOPTIONS_NEWWAYPOINT       40102
#define ID_TOOLS_MOB                    40103
#define ID_TOOLS_SORT_WAYPOINTS         40104
#define ID_TOOLS_SORT_ROUTES            40105
#define ID_TOOLS_SORT_TRACKS            40106
#define ID_TOOLS_SORT_ALL               40107
#define ID_LVPOPUP                      40108
#define IDS_CAP_LVPOPUP                 40109
#define ID_LVPOPUP_GOTO                 40110
#define ID_PVTPOPUP                     40111
#define IDS_CAP_PVTPOPUP                40112
#define ID_PVTOPTIONS                   40113
#define IDS_CAP_PVTOPTIONS              40114
#define ID_PVTOPTIONS_MARK              40115
#define ID_LVPOPUP_CUT                  40116
#define ID_LVPOPUP_COPY                 40117
#define ID_LVPOPUP_PASTE_BEFORE         40118
#define ID_LVPOPUP_PASTE_ON             40119
#define ID_LVPOPUP_PASTE_AFTER          40120
#define ID_LVPOPUP_DELETE               40121
#define ID_LVPOPUP_EDIT                 40122
#define ID_SIPPREF                      40123
#define ID_MAPOPTIONS_EDIT_WAYPOINT     40124
#define ID_MAPOPTIONS_EDIT_ROUTEWAYPOINT 40125
#define ID_MAPOPTIONS_EDIT_TRACKPOINT   40126
#define ID_MAPOPTIONS_EDIT_ROUTE        40127
#define ID_MAPOPTIONS_EDIT_TRACK        40128
#define ID_MAPOPTIONS_GOTO_WAYPOINT     40129
#define ID_MAPOPTIONS_GOTO_ROUTEWAYPOINT 40130
#define ID_MAPOPTIONS_GOTO_TRACKPOINT   40131
#define ID_MAPOPTIONS_MEASURE_START     40132
#define ID_MAPOPTIONS_MEASURE_END       40133
#define ID_MAPOPTIONS_MEASURE_INCREMENT 40134
#define ID_TOOLS_OPTIONS_COMPORT        40135
#define ID_LVPOPUP_NEXTS                40136
#define ID_LVPOPUP_PREVS                40137
#define ID_LVPOPUP_CONVERTALLS          40138
#define ID_LVPOPUP_CONVERTS             40139
#define ID_EDIT_CHECK_EVERYTHING        40140
#define ID_EDIT_CHECK_ALLBOXES          40141
#define ID_EDIT_CHECK_ALLWPTRTETRK      40142
#define ID_EDIT_CHECK_ALLWAYPOINTS      40143
#define ID_EDIT_CHECK_ALLROUTES         40144
#define ID_EDIT_CHECK_ALLTRACKS         40145
#define ID_EDIT_CHECK_ALLTRACKPOINTS    40146
#define ID_EDIT_CHECK_ALLROUTEWAYPOINTS 40147
#define ID_EDIT_CHECK_ALLSELECTED       40148
#define ID_EDIT_CHECK_NOBOXES           40149
#define ID_EDIT_CHECK_NOWPTRTETRK       40150
#define ID_EDIT_CHECK_NOWAYPOINTS       40151
#define ID_EDIT_CHECK_NOROUTES          40152
#define ID_EDIT_CHECK_NOTRACKS          40153
#define ID_EDIT_CHECK_NOTRACKPOINTS     40154
#define ID_EDIT_CHECK_NOROUTEWAYPOINTS  40155
#define ID_EDIT_CHECK_NOSELECTED        40156
#define ID_MAPOPTIONS_ADJUSTGAMMA       40157
#ifndef IDC_STATIC
#define IDC_STATIC			-1
#endif

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        120
#define _APS_NEXT_COMMAND_VALUE         40158
#define _APS_NEXT_CONTROL_VALUE         10062
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
